

! Focussing routine created by EXTRACTPKCN1.FOR
! Ian Harris 1994 (ibh11@cus.cam.ac.uk)
!
! GENIE routine to focus spectra from TEST Beam
!
! Unsmoothed background is not subtracted
! Final spectrum normalised by unsmoothed
!   Vanadium spectrum (#5138)
! Focussed to Detector 70
! Normalised to beam monitor count
!
! Template from KSK and JSW
$ nwork=p1
$ nrun=p2
$ nbin=p3
!
> ass 'nrun'
!
> set par w15 11.1434 0 180.0 0 0
> w15=s70
> u/d w15
> w'nwork'=w15
!
> set par w15 11.8983 0 180.0 0 0
> w15=s3
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8580 0 180.0 0 0
> w15=s4
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8341 0 180.0 0 0
> w15=s5
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7973 0 180.0 0 0
> w15=s6
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7629 0 180.0 0 0
> w15=s7
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7390 0 180.0 0 0
> w15=s8
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7035 0 180.0 0 0
> w15=s9
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.6620 0 180.0 0 0
> w15=s10
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.6340 0 180.0 0 0
> w15=s11
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5975 0 180.0 0 0
> w15=s12
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5676 0 180.0 0 0
> w15=s13
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5265 0 180.0 0 0
> w15=s14
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4941 0 180.0 0 0
> w15=s15
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4550 0 180.0 0 0
> w15=s16
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4299 0 180.0 0 0
> w15=s17
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3882 0 180.0 0 0
> w15=s18
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3573 0 180.0 0 0
> w15=s19
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3201 0 180.0 0 0
> w15=s20
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2858 0 180.0 0 0
> w15=s21
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2491 0 180.0 0 0
> w15=s22
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2203 0 180.0 0 0
> w15=s23
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1816 0 180.0 0 0
> w15=s24
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1498 0 180.0 0 0
> w15=s25
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1083 0 180.0 0 0
> w15=s26
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0724 0 180.0 0 0
> w15=s27
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0394 0 180.0 0 0
> w15=s28
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0064 0 180.0 0 0
> w15=s29
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.9657 0 180.0 0 0
> w15=s30
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.9371 0 180.0 0 0
> w15=s31
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8968 0 180.0 0 0
> w15=s32
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8583 0 180.0 0 0
> w15=s33
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8219 0 180.0 0 0
> w15=s34
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7866 0 180.0 0 0
> w15=s35
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7464 0 180.0 0 0
> w15=s36
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7126 0 180.0 0 0
> w15=s37
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6783 0 180.0 0 0
> w15=s38
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6386 0 180.0 0 0
> w15=s39
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6011 0 180.0 0 0
> w15=s40
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.5664 0 180.0 0 0
> w15=s41
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.5201 0 180.0 0 0
> w15=s42
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4863 0 180.0 0 0
> w15=s43
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4469 0 180.0 0 0
> w15=s44
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4157 0 180.0 0 0
> w15=s45
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.3786 0 180.0 0 0
> w15=s46
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.3356 0 180.0 0 0
> w15=s47
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.9072 0 180.0 0 0
> w15=s48
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8667 0 180.0 0 0
> w15=s49
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8384 0 180.0 0 0
> w15=s50
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8001 0 180.0 0 0
> w15=s51
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7723 0 180.0 0 0
> w15=s52
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7330 0 180.0 0 0
> w15=s53
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7025 0 180.0 0 0
> w15=s54
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.6581 0 180.0 0 0
> w15=s55
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.6281 0 180.0 0 0
> w15=s56
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5961 0 180.0 0 0
> w15=s57
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5657 0 180.0 0 0
> w15=s58
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5268 0 180.0 0 0
> w15=s59
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4925 0 180.0 0 0
> w15=s60
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4546 0 180.0 0 0
> w15=s61
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4277 0 180.0 0 0
> w15=s62
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3899 0 180.0 0 0
> w15=s63
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3557 0 180.0 0 0
> w15=s64
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3157 0 180.0 0 0
> w15=s65
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2789 0 180.0 0 0
> w15=s66
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2412 0 180.0 0 0
> w15=s67
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2134 0 180.0 0 0
> w15=s68
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1748 0 180.0 0 0
> w15=s69
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1039 0 180.0 0 0
> w15=s71
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0730 0 180.0 0 0
> w15=s72
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0304 0 180.0 0 0
> w15=s73
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0015 0 180.0 0 0
> w15=s74
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.9575 0 180.0 0 0
> w15=s75
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.9262 0 180.0 0 0
> w15=s76
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8925 0 180.0 0 0
> w15=s77
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8574 0 180.0 0 0
> w15=s78
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8178 0 180.0 0 0
> w15=s79
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7820 0 180.0 0 0
> w15=s80
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7369 0 180.0 0 0
> w15=s81
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7028 0 180.0 0 0
> w15=s82
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6640 0 180.0 0 0
> w15=s83
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6297 0 180.0 0 0
> w15=s84
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.5891 0 180.0 0 0
> w15=s85
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.5582 0 180.0 0 0
> w15=s86
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.5153 0 180.0 0 0
> w15=s87
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4823 0 180.0 0 0
> w15=s88
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4362 0 180.0 0 0
> w15=s89
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4058 0 180.0 0 0
> w15=s90
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.3590 0 180.0 0 0
> w15=s91
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.3293 0 180.0 0 0
> w15=s92
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.9048 0 180.0 0 0
> w15=s93
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8612 0 180.0 0 0
> w15=s94
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8375 0 180.0 0 0
> w15=s95
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.8062 0 180.0 0 0
> w15=s96
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7722 0 180.0 0 0
> w15=s97
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7261 0 180.0 0 0
> w15=s98
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.7006 0 180.0 0 0
> w15=s99
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.6670 0 180.0 0 0
> w15=s100
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.6289 0 180.0 0 0
> w15=s101
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5945 0 180.0 0 0
> w15=s102
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5683 0 180.0 0 0
> w15=s103
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.5256 0 180.0 0 0
> w15=s104
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4966 0 180.0 0 0
> w15=s105
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4603 0 180.0 0 0
> w15=s106
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.4282 0 180.0 0 0
> w15=s107
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3963 0 180.0 0 0
> w15=s108
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3582 0 180.0 0 0
> w15=s109
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.3163 0 180.0 0 0
> w15=s110
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2878 0 180.0 0 0
> w15=s111
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2484 0 180.0 0 0
> w15=s112
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.2158 0 180.0 0 0
> w15=s113
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1754 0 180.0 0 0
> w15=s114
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1446 0 180.0 0 0
> w15=s115
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.1085 0 180.0 0 0
> w15=s116
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0714 0 180.0 0 0
> w15=s117
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0338 0 180.0 0 0
> w15=s118
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 11.0046 0 180.0 0 0
> w15=s119
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.9639 0 180.0 0 0
> w15=s120
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.9303 0 180.0 0 0
> w15=s121
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8912 0 180.0 0 0
> w15=s122
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8560 0 180.0 0 0
> w15=s123
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.8153 0 180.0 0 0
> w15=s124
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7874 0 180.0 0 0
> w15=s125
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7506 0 180.0 0 0
> w15=s126
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.7160 0 180.0 0 0
> w15=s127
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6784 0 180.0 0 0
> w15=s128
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6446 0 180.0 0 0
> w15=s129
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.6043 0 180.0 0 0
> w15=s130
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.5674 0 180.0 0 0
> w15=s131
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.5314 0 180.0 0 0
> w15=s132
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4925 0 180.0 0 0
> w15=s133
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4557 0 180.0 0 0
> w15=s134
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.4200 0 180.0 0 0
> w15=s135
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.3806 0 180.0 0 0
> w15=s136
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
> set par w15 10.3431 0 180.0 0 0
> w15=s137
> u/d w15
> rebin w'nwork' w15
> w'nwork'=w'nwork'+w15
!
! ***** NORMALIZE TO INCIDENT BEAM MONITOR *****
!
> w15=s1
> integrate w15 5000 5400
> W'NWORK'=W'NWORK'/V1
!
> SET PAR W'NWORK' 15.0 0.7591 90 0 0
> SET YCODE W'NWORK' -1
> U/T W'NWORK'
!
! ***** SUBTRACT INSTRUMENTAL BACKGROUND *****
!
!> read/open w15 teb_calib_empty:ef5137.dat
!> read/close
!> rebin w'nwork' w15
!> w'nwork'=w'nwork'-w15
!
! ***** NORMALIZE TO VANADIUM SPECTRUM *****
!
> read/open w15 teb_calib_van:ef223054.his 1
> read/close
> rebin w'nwork' W15
> w'nwork'=w'nwork'/w15
!
> rebin w'nwork' 1000:19000
!
> a b 'nbin'
> u/t w'nwork'
!