!
! $Id: genie_modules_f90.inc.in,v 1.2 1998/04/27 13:52:44 rgs Exp$
! Modified to allow for F90 style comment lines
!
! Generated automatically from genie_modules.inc.in by configure.
!
! *** Genie version parameters for FORTRAN program include ***
      INTEGER GENIE_MAJOR, GENIE_MINOR, GDIALOGUEBOXSIZE
      PARAMETER(GENIE_MAJOR=1,GENIE_MINOR=2,GDIALOGUEBOXSIZE=50)
! *** module functions ***
      INTEGER MODULE_VERSION_OK
      EXTERNAL MODULE_VERSION_OK
