C
C $Id: genie_modules.inc.in,v 1.2 1998/04/27 13:52:44 rgs Exp $
C
C Generated automatically from genie_modules.inc.in by configure.
C
C *** Genie version parameters for FORTRAN program include ***
      INTEGER GENIE_MAJOR, GENIE_MINOR, GDIALOGUEBOXSIZE
      PARAMETER(GENIE_MAJOR=1,GENIE_MINOR=2,GDIALOGUEBOXSIZE=50)
C *** module functions ***
      INTEGER MODULE_VERSION_OK
      EXTERNAL MODULE_VERSION_OK
